---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv-volume  # Sets PV's name
#   namespace: database
#   labels:
#     type: local  # Sets PV's type to local
#     app: postgres
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 5Gi # Sets PV Volume
#   accessModes:
#     - ReadWriteOnce
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  # Sets name of PVC
  namespace: database
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
---