apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: spacetrouble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: nginx
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 80
            name: nginx-proxy
            protocol: TCP
          - containerPort: 443
            name: nginx-proxy-ssl
            protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: default.conf
              path: default.conf
      - name: secrets
        secret:
          secretName: ssl-proxy-secret