kind: Service
apiVersion: v1
metadata:
  name: nginx-ssl-proxy
  namespace: spacetrouble
  labels:
    app: nginx-proxy
spec:
  selector:
    app: nginx-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer